version: '3.7'

services:
  ghost:
    container_name: ghost
    image: yunfandev/ghost:cloudinary
    restart: always
    environment: 
      - "url=https://example.com"
    volumes:
      - data:/var/lib/ghost/content
      - ./config.production-s3.json:/var/lib/ghost/config.production.json
    networks:
      - app

volumes:
  data:

networks:
  app:
    external: true
