name: Docker Image CI

on:
  schedule:
    - cron: 0 9 * * *
  push:
    branches:
    - master
    - release/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker login
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker login -u $USER_NAME -p $PASSWORD
        docker buildx create --use

    - name: Build the Docker image
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        docker pull $USER_NAME/ghost:cloudinary || :
        docker buildx build --push --platform linux/amd64 --cache-from $USER_NAME/ghost:cloudinary --pull --file Dockerfile --tag $USER_NAME/ghost:cloudinary .