name: Docker Image CI

on:
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
    - master
    - release/*

jobs:

  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        docker login -u $USER_NAME -p $PASSWORD

    - name: Build the Docker image
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        docker pull $USER_NAME/ghost:cloudinary || :
        docker build --cache-from $USER_NAME/ghost:cloudinary --pull . --file Dockerfile --tag $USER_NAME/ghost:cloudinary
        docker push $USER_NAME/ghost:cloudinary

    - name: Build the v3 Docker image
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        docker pull $USER_NAME/ghost:3-cloudinary || :
        docker build --cache-from $USER_NAME/ghost:3-cloudinary --pull . --file Dockerfile.v3 --tag $USER_NAME/ghost:3-cloudinary
        docker push $USER_NAME/ghost:3-cloudinary

    - name: Docker logout
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        docker logout